[project]
name = "glassbox"
version = "0.1.0"
description = "Plateforme Ã©ducative pour rÃ©seaux de neurones"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "pandas",
  "scikit-learn",
  "streamlit",
  "plotly",
  "sympy==1.13.1",
]
